API_KEY = 'API KEY HERE'
URL_BASE = "https://www.virustotal.com/vtapi/v2/url/report"
PUBLIC_API_SLEEP_TIME = 60
PUBLIC_API_REQUEST_PER_MIN = 4
PRODUCED_CODE = 200
QUOTA_CODE = 204
BAD_VALUES_CODE = 400
FORBIDDEN_CODE = 403